# Generated by Django 3.1.2 on 2020-11-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdminUser', models.CharField(max_length=5)),
                ('AdminPass', models.CharField(default='123456', max_length=10)),
                ('AdminCollege', models.CharField(default='hbu', max_length=10)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
