# Generated by Django 3.1.2 on 2020-11-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStudent',
            fields=[
                ('StuNum', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('StuName', models.FloatField(max_length=10)),
                ('StuAge', models.IntegerField(max_length=10)),
                ('StuSex', models.CharField(max_length=10)),
                ('StuBirth', models.DateField()),
                ('StuCollege', models.CharField(max_length=10)),
                ('StuPass', models.CharField(max_length=10)),
                ('StuMajor', models.CharField(max_length=10)),
                ('StuGra', models.BooleanField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
