# Generated by Django 3.1.2 on 2020-11-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affairstudent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstudent',
            name='StuName',
            field=models.CharField(max_length=10),
        ),
    ]
