# Generated by Django 3.1.2 on 2020-11-16 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affairstudent', '0003_auto_20201113_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentstudent',
            name='StuBirth',
        ),
    ]
