# Generated by Django 3.1.2 on 2020-11-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourName', models.CharField(max_length=10)),
                ('CourCredit', models.FloatField(max_length=10)),
                ('CourPlace', models.CharField(max_length=10)),
                ('CourType', models.CharField(max_length=10)),
                ('CourReq', models.CharField(max_length=10)),
                ('CourTea', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
