# Generated by Django 3.1.2 on 2020-11-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaircourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='CourNum',
            field=models.IntegerField(default=0),
        ),
    ]
