# Generated by Django 3.1.2 on 2020-11-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaircourse', '0002_auto_20201114_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
