# Generated by Django 3.1.2 on 2020-11-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaircourse', '0003_auto_20201116_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='Ispass',
            field=models.BooleanField(default=False),
        ),
    ]
