# Generated by Django 3.1.2 on 2020-11-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaircourse', '0004_studentcourse_ispass'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='CourNum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
