# Generated by Django 3.1.2 on 2020-11-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuNum', models.CharField(max_length=10)),
                ('StuName', models.CharField(max_length=10)),
                ('CourNum', models.IntegerField(max_length=10)),
                ('CourName', models.CharField(max_length=10)),
                ('CourGrade', models.FloatField(default=0)),
                ('CourTea', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'student-course',
            },
        ),
    ]
