# Generated by Django 3.1.2 on 2020-11-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStudent',
            fields=[
                ('TeaNum', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TeaName', models.CharField(max_length=10)),
                ('TeaPass', models.CharField(max_length=10)),
                ('TeaCollege', models.CharField(max_length=10)),
                ('TeaMajor', models.CharField(max_length=10)),
                ('TeaSex', models.CharField(max_length=10)),
                ('TeaBirth', models.DateField()),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
