# Generated by Django 3.1.2 on 2020-11-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affairteacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTeacher',
            fields=[
                ('TeaNum', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TeaName', models.CharField(max_length=10)),
                ('TeaPass', models.CharField(max_length=10)),
                ('TeaCollege', models.CharField(max_length=10)),
                ('TeaMajor', models.CharField(max_length=10)),
                ('TeaSex', models.CharField(max_length=10)),
                ('TeaBirth', models.DateField()),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.DeleteModel(
            name='StudentStudent',
        ),
    ]
